version: "3"

services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
      - MYSQL_USERNAME=petclinic
      - MYSQL_PASSWORD=petclinic
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    networks:
      - petclinic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mysqlserver:
    image: hlebsur/mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - petclinic

volumes:
  mysql_data:
  mysql_config:

networks:
  petclinic:
    driver: bridge
